program ::= command {EOL{EOL} command}
command ::= (globals | fun | label | instruction)

globals ::= "globals" "=" natural

fun ::= ".fun" identifier {fun_args}
fun_args ::= ":" fun_arg ["," fun_arg] ";"
fun_arg ::= identifier ":" identifier

label ::= "->" identifier

instruction ::= opcode instruction_args
opcode ::= identifier
instruction_args ::= [operand {"," operand}]
operand ::= identifier | number

identifier ::= identifier_begin | {identifier_rest}
identifier_begin ::= LETTER | "_"
identifier_rest ::= identifier_begin | DIGIT
number ::= ["-"]natural
natural ::= DIGIT{DIGIT}