program ::= command {EOL{EOL} command}
command ::= (fun | label | instruction)
fun ::= ".fun" identifier [":" (args["," locals])|locals]
args ::= "args" "=" natural
locals ::= "locals" "=" natural
label ::= "->" identifier
instruction ::= opcode [operand {"," operand}]
opcode ::= identifier
identifier ::= identifier_begin | {identifier_rest}
identifier_begin ::= LETTER | "_"
identifier_rest ::= identifier_begin | DIGIT
operand ::= identifier | number
number ::= ["-"]natural
natural ::= DIGIT{DIGIT}